import "./globals.css";

import { Open_Sans } from "next/font/google";

import Header from "../components/header/Header";
// import useIsVisible from "../container/hooks/useIsVisible ";
import Footer from "../components/footer/Footer";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

// export const metadata = {
//   title: "blog",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={openSans.className}>
      <body cz-shortcut-listen="true" className="bg-[#F5F5F5]">
        <div className="">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
